### ISSUE TITLE
SyntaxError: Unexpected character '' (2:0) while parsing htmlstrip-native/build/Release/htmlstrip.node

### ISSUE THREAD

**Issue by dzoba** [zaro/node-htmlstrip-native#13]
I keep running in to this error when trying to use htmlstrip-native.  Any one else?

```
[16:18:05] SyntaxError: Unexpected character '' (2:0) while parsing /vagrant/src/ganges/node_modules/htmlstrip-native/build/Release/htmlstrip.node while parsing file: /vagrant/src/ganges/node_modules/htmlstrip-native/build/Release/htmlstrip.node
    at Stream.end (/vagrant/src/ganges/node_modules/browserify/node_modules/insert-module-globals/index.js:75:21)
    at _end (/vagrant/src/ganges/node_modules/browserify/node_modules/insert-module-globals/node_modules/through/index.js:65:9)
    at Stream.stream.end (/vagrant/src/ganges/node_modules/browserify/node_modules/insert-module-globals/node_modules/through/index.js:74:5)
    at Transform.onend (/vagrant/src/ganges/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:180:16)
    at Transform.emit (events.js:117:20)
    at /vagrant/src/ganges/node_modules/browserify/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:442:13)

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Cannot find module './build/Debug/htmlstrip.node' from '/vagrant/src/ganges/node_modules/htmlstrip-native'
    at /vagrant/src/ganges/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:21
    at load (/vagrant/src/ganges/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/vagrant/src/ganges/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /vagrant/src/ganges/node_modules/browserify/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:108:15)
```

**Comment by zaro** [comment]
Hi,

Are you truing to use this module with browserify ?
If you do, you should know it doesn't work, as it is native C++ library,
and not JS, so it won't work in the browser.

Cheers,
Zaro

**Comment by dzoba** [comment]
Ah, right.  Thanks!  Also thanks for responding so quickly :)  Closing.
