### ISSUE TITLE
Failed at the htmlstrip-native@0.1.1 install script 'node-gyp rebuild'.

### ISSUE THREAD

**Issue by paulsheldrake** [zaro/node-htmlstrip-native#16]
I have attached my NPM debug log

[npm-debug.log.zip](https://github.com/zaro/node-htmlstrip-native/files/166694/npm-debug.log.zip)

**Comment by zaro** [comment]
can you check if you have node-gyp dependencies installed: 

https://github.com/nodejs/node-gyp#installation

I see you use Mac OS X , so you have python for sure, but maybe XCode Command Line Tools  are missing.
Because there is no real error in the nodule, only node-gyp error.

**Comment by esatterwhite** [comment]
@zaro  I have this problem to on linux

using node 4.2.4

**Comment by zaro** [comment]
@esatterwhite can you provide npm-debug.log ?

**Comment by esatterwhite** [comment]
[npm-debug.zip](https://github.com/zaro/node-htmlstrip-native/files/197994/npm-debug.zip)

**Comment by zaro** [comment]
OK, it seems like its the same problem.
Do you have the prerequisites  for node-gyp as  listed here : https://github.com/nodejs/node-gyp#installation

- python 2.7 
- make
- gcc/g++

If you are using Ubuntu you have Python already, so you can just do :

    apt-get install g++ make

**Comment by esatterwhite** [comment]
no, arch. And all of that is installed. I  build other native modules just fine

**Comment by esatterwhite** [comment]
this does install with iojs v2.5, 3.4 and other versions of node.

There is something you must not be accounting for with the 4.2.x version... (?)

**Comment by zaro** [comment]
Well I just tried on clean Ubuntu with 4.2.4 and everything was fine.

The npm-debug.log is missing the actual node-gyp output and  errors.
Can you paste, or attach here, the terminal output of  npm install htmlstrip-native ?

**Comment by esatterwhite** [comment]
```
> htmlstrip-native@0.1.3 install /home/esatterwhite/dev/js/fulfill/yarn/node_modules/htmlstrip-native
> node-gyp rebuild

gyp: /home/esatterwhite/.node-gyp/4.2.4/common.gypi not found (cwd: /home/esatterwhite/dev/js/fulfill/yarn/node_modules/htmlstrip-native) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/esatterwhite/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:357:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.3.3-2-ARCH
gyp ERR! command "/home/esatterwhite/.nvm/versions/node/v4.2.4/bin/node" "/home/esatterwhite/.nvm/versions/node/v4.2.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/esatterwhite/dev/js/fulfill/yarn/node_modules/htmlstrip-native
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm ERR! Linux 4.3.3-2-ARCH
npm ERR! argv "/home/esatterwhite/.nvm/versions/node/v4.2.4/bin/node" "/home/esatterwhite/.nvm/versions/node/v4.2.4/bin/npm" "install" "htmlstrip-native"
npm ERR! node v4.2.4
npm ERR! npm  v2.14.1
npm ERR! code ELIFECYCLE

npm ERR! htmlstrip-native@0.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the htmlstrip-native@0.1.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the htmlstrip-native package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls htmlstrip-native
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/esatterwhite/dev/js/fulfill/yarn/npm-debug.log

```

**Comment by zaro** [comment]
Definitely problem with node-gyp or how it is installed not the module itself.

    gyp: /home/esatterwhite/.node-gyp/4.2.4/common.gypi not found (cwd: /home/esatterwhite/dev/js/fulfill/yarn/node_modules/htmlstrip-native) while reading includes of binding.gyp while trying to load binding.gyp

This issues : https://github.com/nodejs/node-gyp/issues/313 , https://github.com/nodejs/node-gyp/issues/819  seem related.
How did you install node/npm ?

**Comment by esatterwhite** [comment]
I used nvm 

`nvm install v4.2`

**Comment by zaro** [comment]
I also used nvm to test on Ubuntu.
Unfortunately I am out of ideas, as this is something related to node-gyp , and I am not that familiar with it.

**Comment by polkolins** [comment]
I have attached my NPM debug log
I have no idea how to fix this
• Windows 10
• htmlstrip-native@0.1.3
• node v5.10
• C++ is installed
• python 2.7
[npm-debug.zip](https://github.com/zaro/node-htmlstrip-native/files/208316/npm-debug.zip)

**Comment by vot** [comment]
I had the same issue today. What worked for me was removing the .node-gyp folder (next time node-gyp is called it will rebuild it).

Look for the line with `./node-gyp` in your log and remove that folder (something like `rm -rf ~/.node-gyp`)
